# Generated by Django 5.1.4 on 2025-01-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_tasks_category_tasks_created_tasks_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='category',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Others', 'Others')], max_length=8),
        ),
    ]
