# Generated by Django 5.1.4 on 2025-01-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_alter_tasks_options_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='email_varified',
            field=models.BooleanField(default=False),
        ),
    ]
